dist: trusty
sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests

after_success:
  - coveralls --root .. --gcov-options '\-lp' -e example -E '.*.h' -E '.*.cpp' -E '.*.cc'
