# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/simul/lwmqtt/256dpi/lwmqtt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/simul/lwmqtt/256dpi/lwmqtt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/simul/lwmqtt/256dpi/lwmqtt/CMakeFiles /data/simul/lwmqtt/256dpi/lwmqtt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/simul/lwmqtt/256dpi/lwmqtt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named example-async

# Build rule for target.
example-async: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example-async
.PHONY : example-async

# fast build rule for target.
example-async/fast:
	$(MAKE) -f CMakeFiles/example-async.dir/build.make CMakeFiles/example-async.dir/build
.PHONY : example-async/fast

#=============================================================================
# Target rules for targets named example-sync

# Build rule for target.
example-sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example-sync
.PHONY : example-sync

# fast build rule for target.
example-sync/fast:
	$(MAKE) -f CMakeFiles/example-sync.dir/build.make CMakeFiles/example-sync.dir/build
.PHONY : example-sync/fast

#=============================================================================
# Target rules for targets named lwmqtt_d

# Build rule for target.
lwmqtt_d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lwmqtt_d
.PHONY : lwmqtt_d

# fast build rule for target.
lwmqtt_d/fast:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/build
.PHONY : lwmqtt_d/fast

#=============================================================================
# Target rules for targets named lwmqtt

# Build rule for target.
lwmqtt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lwmqtt
.PHONY : lwmqtt

# fast build rule for target.
lwmqtt/fast:
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/build
.PHONY : lwmqtt/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f gtest/googletest/CMakeFiles/gtest_main.dir/build.make gtest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f gtest/googletest/CMakeFiles/gtest.dir/build.make gtest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

examples/async.o: examples/async.c.o

.PHONY : examples/async.o

# target to build an object file
examples/async.c.o:
	$(MAKE) -f CMakeFiles/example-async.dir/build.make CMakeFiles/example-async.dir/examples/async.c.o
.PHONY : examples/async.c.o

examples/async.i: examples/async.c.i

.PHONY : examples/async.i

# target to preprocess a source file
examples/async.c.i:
	$(MAKE) -f CMakeFiles/example-async.dir/build.make CMakeFiles/example-async.dir/examples/async.c.i
.PHONY : examples/async.c.i

examples/async.s: examples/async.c.s

.PHONY : examples/async.s

# target to generate assembly for a file
examples/async.c.s:
	$(MAKE) -f CMakeFiles/example-async.dir/build.make CMakeFiles/example-async.dir/examples/async.c.s
.PHONY : examples/async.c.s

examples/sync.o: examples/sync.c.o

.PHONY : examples/sync.o

# target to build an object file
examples/sync.c.o:
	$(MAKE) -f CMakeFiles/example-sync.dir/build.make CMakeFiles/example-sync.dir/examples/sync.c.o
.PHONY : examples/sync.c.o

examples/sync.i: examples/sync.c.i

.PHONY : examples/sync.i

# target to preprocess a source file
examples/sync.c.i:
	$(MAKE) -f CMakeFiles/example-sync.dir/build.make CMakeFiles/example-sync.dir/examples/sync.c.i
.PHONY : examples/sync.c.i

examples/sync.s: examples/sync.c.s

.PHONY : examples/sync.s

# target to generate assembly for a file
examples/sync.c.s:
	$(MAKE) -f CMakeFiles/example-sync.dir/build.make CMakeFiles/example-sync.dir/examples/sync.c.s
.PHONY : examples/sync.c.s

src/client.o: src/client.c.o

.PHONY : src/client.o

# target to build an object file
src/client.c.o:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/client.c.o
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/client.c.o
.PHONY : src/client.c.o

src/client.i: src/client.c.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.c.i:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/client.c.i
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/client.c.i
.PHONY : src/client.c.i

src/client.s: src/client.c.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.c.s:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/client.c.s
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/client.c.s
.PHONY : src/client.c.s

src/helpers.o: src/helpers.c.o

.PHONY : src/helpers.o

# target to build an object file
src/helpers.c.o:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/helpers.c.o
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/helpers.c.o
.PHONY : src/helpers.c.o

src/helpers.i: src/helpers.c.i

.PHONY : src/helpers.i

# target to preprocess a source file
src/helpers.c.i:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/helpers.c.i
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/helpers.c.i
.PHONY : src/helpers.c.i

src/helpers.s: src/helpers.c.s

.PHONY : src/helpers.s

# target to generate assembly for a file
src/helpers.c.s:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/helpers.c.s
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/helpers.c.s
.PHONY : src/helpers.c.s

src/os/unix.o: src/os/unix.c.o

.PHONY : src/os/unix.o

# target to build an object file
src/os/unix.c.o:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/os/unix.c.o
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/os/unix.c.o
.PHONY : src/os/unix.c.o

src/os/unix.i: src/os/unix.c.i

.PHONY : src/os/unix.i

# target to preprocess a source file
src/os/unix.c.i:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/os/unix.c.i
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/os/unix.c.i
.PHONY : src/os/unix.c.i

src/os/unix.s: src/os/unix.c.s

.PHONY : src/os/unix.s

# target to generate assembly for a file
src/os/unix.c.s:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/os/unix.c.s
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/os/unix.c.s
.PHONY : src/os/unix.c.s

src/packet.o: src/packet.c.o

.PHONY : src/packet.o

# target to build an object file
src/packet.c.o:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/packet.c.o
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/packet.c.o
.PHONY : src/packet.c.o

src/packet.i: src/packet.c.i

.PHONY : src/packet.i

# target to preprocess a source file
src/packet.c.i:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/packet.c.i
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/packet.c.i
.PHONY : src/packet.c.i

src/packet.s: src/packet.c.s

.PHONY : src/packet.s

# target to generate assembly for a file
src/packet.c.s:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/packet.c.s
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/packet.c.s
.PHONY : src/packet.c.s

src/string.o: src/string.c.o

.PHONY : src/string.o

# target to build an object file
src/string.c.o:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/string.c.o
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/string.c.o
.PHONY : src/string.c.o

src/string.i: src/string.c.i

.PHONY : src/string.i

# target to preprocess a source file
src/string.c.i:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/string.c.i
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/string.c.i
.PHONY : src/string.c.i

src/string.s: src/string.c.s

.PHONY : src/string.s

# target to generate assembly for a file
src/string.c.s:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/string.c.s
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/string.c.s
.PHONY : src/string.c.s

tests1/client.o: tests1/client.cpp.o

.PHONY : tests1/client.o

# target to build an object file
tests1/client.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/client.cpp.o
.PHONY : tests1/client.cpp.o

tests1/client.i: tests1/client.cpp.i

.PHONY : tests1/client.i

# target to preprocess a source file
tests1/client.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/client.cpp.i
.PHONY : tests1/client.cpp.i

tests1/client.s: tests1/client.cpp.s

.PHONY : tests1/client.s

# target to generate assembly for a file
tests1/client.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/client.cpp.s
.PHONY : tests1/client.cpp.s

tests1/helpers.o: tests1/helpers.cpp.o

.PHONY : tests1/helpers.o

# target to build an object file
tests1/helpers.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/helpers.cpp.o
.PHONY : tests1/helpers.cpp.o

tests1/helpers.i: tests1/helpers.cpp.i

.PHONY : tests1/helpers.i

# target to preprocess a source file
tests1/helpers.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/helpers.cpp.i
.PHONY : tests1/helpers.cpp.i

tests1/helpers.s: tests1/helpers.cpp.s

.PHONY : tests1/helpers.s

# target to generate assembly for a file
tests1/helpers.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/helpers.cpp.s
.PHONY : tests1/helpers.cpp.s

tests1/packet.o: tests1/packet.cpp.o

.PHONY : tests1/packet.o

# target to build an object file
tests1/packet.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/packet.cpp.o
.PHONY : tests1/packet.cpp.o

tests1/packet.i: tests1/packet.cpp.i

.PHONY : tests1/packet.i

# target to preprocess a source file
tests1/packet.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/packet.cpp.i
.PHONY : tests1/packet.cpp.i

tests1/packet.s: tests1/packet.cpp.s

.PHONY : tests1/packet.s

# target to generate assembly for a file
tests1/packet.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/packet.cpp.s
.PHONY : tests1/packet.cpp.s

tests1/string.o: tests1/string.cpp.o

.PHONY : tests1/string.o

# target to build an object file
tests1/string.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/string.cpp.o
.PHONY : tests1/string.cpp.o

tests1/string.i: tests1/string.cpp.i

.PHONY : tests1/string.i

# target to preprocess a source file
tests1/string.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/string.cpp.i
.PHONY : tests1/string.cpp.i

tests1/string.s: tests1/string.cpp.s

.PHONY : tests1/string.s

# target to generate assembly for a file
tests1/string.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/string.cpp.s
.PHONY : tests1/string.cpp.s

tests1/tests.o: tests1/tests.cpp.o

.PHONY : tests1/tests.o

# target to build an object file
tests1/tests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/tests.cpp.o
.PHONY : tests1/tests.cpp.o

tests1/tests.i: tests1/tests.cpp.i

.PHONY : tests1/tests.i

# target to preprocess a source file
tests1/tests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/tests.cpp.i
.PHONY : tests1/tests.cpp.i

tests1/tests.s: tests1/tests.cpp.s

.PHONY : tests1/tests.s

# target to generate assembly for a file
tests1/tests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests1/tests.cpp.s
.PHONY : tests1/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tests"
	@echo "... example-async"
	@echo "... example-sync"
	@echo "... lwmqtt_d"
	@echo "... lwmqtt"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... examples/async.o"
	@echo "... examples/async.i"
	@echo "... examples/async.s"
	@echo "... examples/sync.o"
	@echo "... examples/sync.i"
	@echo "... examples/sync.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/helpers.o"
	@echo "... src/helpers.i"
	@echo "... src/helpers.s"
	@echo "... src/os/unix.o"
	@echo "... src/os/unix.i"
	@echo "... src/os/unix.s"
	@echo "... src/packet.o"
	@echo "... src/packet.i"
	@echo "... src/packet.s"
	@echo "... src/string.o"
	@echo "... src/string.i"
	@echo "... src/string.s"
	@echo "... tests1/client.o"
	@echo "... tests1/client.i"
	@echo "... tests1/client.s"
	@echo "... tests1/helpers.o"
	@echo "... tests1/helpers.i"
	@echo "... tests1/helpers.s"
	@echo "... tests1/packet.o"
	@echo "... tests1/packet.i"
	@echo "... tests1/packet.s"
	@echo "... tests1/string.o"
	@echo "... tests1/string.i"
	@echo "... tests1/string.s"
	@echo "... tests1/tests.o"
	@echo "... tests1/tests.i"
	@echo "... tests1/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

