# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/simul/lwmqtt/256dpi/lwmqtt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/simul/lwmqtt/256dpi/lwmqtt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/simul/lwmqtt/256dpi/lwmqtt/CMakeFiles /data/simul/lwmqtt/256dpi/lwmqtt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/simul/lwmqtt/256dpi/lwmqtt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests_app

# Build rule for target.
tests_app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests_app
.PHONY : tests_app

# fast build rule for target.
tests_app/fast:
	$(MAKE) -f CMakeFiles/tests_app.dir/build.make CMakeFiles/tests_app.dir/build
.PHONY : tests_app/fast

#=============================================================================
# Target rules for targets named ben

# Build rule for target.
ben: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ben
.PHONY : ben

# fast build rule for target.
ben/fast:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/build
.PHONY : ben/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named example-async

# Build rule for target.
example-async: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example-async
.PHONY : example-async

# fast build rule for target.
example-async/fast:
	$(MAKE) -f CMakeFiles/example-async.dir/build.make CMakeFiles/example-async.dir/build
.PHONY : example-async/fast

#=============================================================================
# Target rules for targets named example-sync

# Build rule for target.
example-sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example-sync
.PHONY : example-sync

# fast build rule for target.
example-sync/fast:
	$(MAKE) -f CMakeFiles/example-sync.dir/build.make CMakeFiles/example-sync.dir/build
.PHONY : example-sync/fast

#=============================================================================
# Target rules for targets named lwmqtt_d

# Build rule for target.
lwmqtt_d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lwmqtt_d
.PHONY : lwmqtt_d

# fast build rule for target.
lwmqtt_d/fast:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/build
.PHONY : lwmqtt_d/fast

#=============================================================================
# Target rules for targets named lwmqtt

# Build rule for target.
lwmqtt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lwmqtt
.PHONY : lwmqtt

# fast build rule for target.
lwmqtt/fast:
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/build
.PHONY : lwmqtt/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f gtest/googletest/CMakeFiles/gtest_main.dir/build.make gtest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f gtest/googletest/CMakeFiles/gtest.dir/build.make gtest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f _deps/zlib-build/CMakeFiles/zlib.dir/build.make _deps/zlib-build/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f _deps/curl-build/CMakeFiles/uninstall.dir/build.make _deps/curl-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named libcurl

# Build rule for target.
libcurl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libcurl
.PHONY : libcurl

# fast build rule for target.
libcurl/fast:
	$(MAKE) -f _deps/curl-build/lib/CMakeFiles/libcurl.dir/build.make _deps/curl-build/lib/CMakeFiles/libcurl.dir/build
.PHONY : libcurl/fast

#=============================================================================
# Target rules for targets named cpr

# Build rule for target.
cpr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpr
.PHONY : cpr

# fast build rule for target.
cpr/fast:
	$(MAKE) -f _deps/cpr-build/cpr/CMakeFiles/cpr.dir/build.make _deps/cpr-build/cpr/CMakeFiles/cpr.dir/build
.PHONY : cpr/fast

ben_d/CloudConnect.o: ben_d/CloudConnect.cpp.o

.PHONY : ben_d/CloudConnect.o

# target to build an object file
ben_d/CloudConnect.cpp.o:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/CloudConnect.cpp.o
.PHONY : ben_d/CloudConnect.cpp.o

ben_d/CloudConnect.i: ben_d/CloudConnect.cpp.i

.PHONY : ben_d/CloudConnect.i

# target to preprocess a source file
ben_d/CloudConnect.cpp.i:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/CloudConnect.cpp.i
.PHONY : ben_d/CloudConnect.cpp.i

ben_d/CloudConnect.s: ben_d/CloudConnect.cpp.s

.PHONY : ben_d/CloudConnect.s

# target to generate assembly for a file
ben_d/CloudConnect.cpp.s:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/CloudConnect.cpp.s
.PHONY : ben_d/CloudConnect.cpp.s

ben_d/MQTTClient.o: ben_d/MQTTClient.cpp.o

.PHONY : ben_d/MQTTClient.o

# target to build an object file
ben_d/MQTTClient.cpp.o:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/MQTTClient.cpp.o
.PHONY : ben_d/MQTTClient.cpp.o

ben_d/MQTTClient.i: ben_d/MQTTClient.cpp.i

.PHONY : ben_d/MQTTClient.i

# target to preprocess a source file
ben_d/MQTTClient.cpp.i:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/MQTTClient.cpp.i
.PHONY : ben_d/MQTTClient.cpp.i

ben_d/MQTTClient.s: ben_d/MQTTClient.cpp.s

.PHONY : ben_d/MQTTClient.s

# target to generate assembly for a file
ben_d/MQTTClient.cpp.s:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/MQTTClient.cpp.s
.PHONY : ben_d/MQTTClient.cpp.s

ben_d/SSLConnection.o: ben_d/SSLConnection.cpp.o

.PHONY : ben_d/SSLConnection.o

# target to build an object file
ben_d/SSLConnection.cpp.o:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/SSLConnection.cpp.o
.PHONY : ben_d/SSLConnection.cpp.o

ben_d/SSLConnection.i: ben_d/SSLConnection.cpp.i

.PHONY : ben_d/SSLConnection.i

# target to preprocess a source file
ben_d/SSLConnection.cpp.i:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/SSLConnection.cpp.i
.PHONY : ben_d/SSLConnection.cpp.i

ben_d/SSLConnection.s: ben_d/SSLConnection.cpp.s

.PHONY : ben_d/SSLConnection.s

# target to generate assembly for a file
ben_d/SSLConnection.cpp.s:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/SSLConnection.cpp.s
.PHONY : ben_d/SSLConnection.cpp.s

ben_d/Socket.o: ben_d/Socket.cpp.o

.PHONY : ben_d/Socket.o

# target to build an object file
ben_d/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/Socket.cpp.o
.PHONY : ben_d/Socket.cpp.o

ben_d/Socket.i: ben_d/Socket.cpp.i

.PHONY : ben_d/Socket.i

# target to preprocess a source file
ben_d/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/Socket.cpp.i
.PHONY : ben_d/Socket.cpp.i

ben_d/Socket.s: ben_d/Socket.cpp.s

.PHONY : ben_d/Socket.s

# target to generate assembly for a file
ben_d/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/Socket.cpp.s
.PHONY : ben_d/Socket.cpp.s

ben_d/main.o: ben_d/main.cpp.o

.PHONY : ben_d/main.o

# target to build an object file
ben_d/main.cpp.o:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/main.cpp.o
.PHONY : ben_d/main.cpp.o

ben_d/main.i: ben_d/main.cpp.i

.PHONY : ben_d/main.i

# target to preprocess a source file
ben_d/main.cpp.i:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/main.cpp.i
.PHONY : ben_d/main.cpp.i

ben_d/main.s: ben_d/main.cpp.s

.PHONY : ben_d/main.s

# target to generate assembly for a file
ben_d/main.cpp.s:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/main.cpp.s
.PHONY : ben_d/main.cpp.s

ben_d/mainAruba.o: ben_d/mainAruba.cpp.o

.PHONY : ben_d/mainAruba.o

# target to build an object file
ben_d/mainAruba.cpp.o:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/mainAruba.cpp.o
.PHONY : ben_d/mainAruba.cpp.o

ben_d/mainAruba.i: ben_d/mainAruba.cpp.i

.PHONY : ben_d/mainAruba.i

# target to preprocess a source file
ben_d/mainAruba.cpp.i:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/mainAruba.cpp.i
.PHONY : ben_d/mainAruba.cpp.i

ben_d/mainAruba.s: ben_d/mainAruba.cpp.s

.PHONY : ben_d/mainAruba.s

# target to generate assembly for a file
ben_d/mainAruba.cpp.s:
	$(MAKE) -f CMakeFiles/ben.dir/build.make CMakeFiles/ben.dir/ben_d/mainAruba.cpp.s
.PHONY : ben_d/mainAruba.cpp.s

examples/async.o: examples/async.c.o

.PHONY : examples/async.o

# target to build an object file
examples/async.c.o:
	$(MAKE) -f CMakeFiles/example-async.dir/build.make CMakeFiles/example-async.dir/examples/async.c.o
.PHONY : examples/async.c.o

examples/async.i: examples/async.c.i

.PHONY : examples/async.i

# target to preprocess a source file
examples/async.c.i:
	$(MAKE) -f CMakeFiles/example-async.dir/build.make CMakeFiles/example-async.dir/examples/async.c.i
.PHONY : examples/async.c.i

examples/async.s: examples/async.c.s

.PHONY : examples/async.s

# target to generate assembly for a file
examples/async.c.s:
	$(MAKE) -f CMakeFiles/example-async.dir/build.make CMakeFiles/example-async.dir/examples/async.c.s
.PHONY : examples/async.c.s

examples/sync.o: examples/sync.c.o

.PHONY : examples/sync.o

# target to build an object file
examples/sync.c.o:
	$(MAKE) -f CMakeFiles/example-sync.dir/build.make CMakeFiles/example-sync.dir/examples/sync.c.o
.PHONY : examples/sync.c.o

examples/sync.i: examples/sync.c.i

.PHONY : examples/sync.i

# target to preprocess a source file
examples/sync.c.i:
	$(MAKE) -f CMakeFiles/example-sync.dir/build.make CMakeFiles/example-sync.dir/examples/sync.c.i
.PHONY : examples/sync.c.i

examples/sync.s: examples/sync.c.s

.PHONY : examples/sync.s

# target to generate assembly for a file
examples/sync.c.s:
	$(MAKE) -f CMakeFiles/example-sync.dir/build.make CMakeFiles/example-sync.dir/examples/sync.c.s
.PHONY : examples/sync.c.s

src/client.o: src/client.c.o

.PHONY : src/client.o

# target to build an object file
src/client.c.o:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/client.c.o
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/client.c.o
.PHONY : src/client.c.o

src/client.i: src/client.c.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.c.i:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/client.c.i
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/client.c.i
.PHONY : src/client.c.i

src/client.s: src/client.c.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.c.s:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/client.c.s
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/client.c.s
.PHONY : src/client.c.s

src/helpers.o: src/helpers.c.o

.PHONY : src/helpers.o

# target to build an object file
src/helpers.c.o:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/helpers.c.o
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/helpers.c.o
.PHONY : src/helpers.c.o

src/helpers.i: src/helpers.c.i

.PHONY : src/helpers.i

# target to preprocess a source file
src/helpers.c.i:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/helpers.c.i
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/helpers.c.i
.PHONY : src/helpers.c.i

src/helpers.s: src/helpers.c.s

.PHONY : src/helpers.s

# target to generate assembly for a file
src/helpers.c.s:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/helpers.c.s
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/helpers.c.s
.PHONY : src/helpers.c.s

src/os/unix.o: src/os/unix.c.o

.PHONY : src/os/unix.o

# target to build an object file
src/os/unix.c.o:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/os/unix.c.o
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/os/unix.c.o
.PHONY : src/os/unix.c.o

src/os/unix.i: src/os/unix.c.i

.PHONY : src/os/unix.i

# target to preprocess a source file
src/os/unix.c.i:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/os/unix.c.i
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/os/unix.c.i
.PHONY : src/os/unix.c.i

src/os/unix.s: src/os/unix.c.s

.PHONY : src/os/unix.s

# target to generate assembly for a file
src/os/unix.c.s:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/os/unix.c.s
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/os/unix.c.s
.PHONY : src/os/unix.c.s

src/packet.o: src/packet.c.o

.PHONY : src/packet.o

# target to build an object file
src/packet.c.o:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/packet.c.o
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/packet.c.o
.PHONY : src/packet.c.o

src/packet.i: src/packet.c.i

.PHONY : src/packet.i

# target to preprocess a source file
src/packet.c.i:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/packet.c.i
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/packet.c.i
.PHONY : src/packet.c.i

src/packet.s: src/packet.c.s

.PHONY : src/packet.s

# target to generate assembly for a file
src/packet.c.s:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/packet.c.s
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/packet.c.s
.PHONY : src/packet.c.s

src/string.o: src/string.c.o

.PHONY : src/string.o

# target to build an object file
src/string.c.o:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/string.c.o
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/string.c.o
.PHONY : src/string.c.o

src/string.i: src/string.c.i

.PHONY : src/string.i

# target to preprocess a source file
src/string.c.i:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/string.c.i
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/string.c.i
.PHONY : src/string.c.i

src/string.s: src/string.c.s

.PHONY : src/string.s

# target to generate assembly for a file
src/string.c.s:
	$(MAKE) -f CMakeFiles/lwmqtt_d.dir/build.make CMakeFiles/lwmqtt_d.dir/src/string.c.s
	$(MAKE) -f CMakeFiles/lwmqtt.dir/build.make CMakeFiles/lwmqtt.dir/src/string.c.s
.PHONY : src/string.c.s

tests_ben/client.o: tests_ben/client.cpp.o

.PHONY : tests_ben/client.o

# target to build an object file
tests_ben/client.cpp.o:
	$(MAKE) -f CMakeFiles/tests_app.dir/build.make CMakeFiles/tests_app.dir/tests_ben/client.cpp.o
.PHONY : tests_ben/client.cpp.o

tests_ben/client.i: tests_ben/client.cpp.i

.PHONY : tests_ben/client.i

# target to preprocess a source file
tests_ben/client.cpp.i:
	$(MAKE) -f CMakeFiles/tests_app.dir/build.make CMakeFiles/tests_app.dir/tests_ben/client.cpp.i
.PHONY : tests_ben/client.cpp.i

tests_ben/client.s: tests_ben/client.cpp.s

.PHONY : tests_ben/client.s

# target to generate assembly for a file
tests_ben/client.cpp.s:
	$(MAKE) -f CMakeFiles/tests_app.dir/build.make CMakeFiles/tests_app.dir/tests_ben/client.cpp.s
.PHONY : tests_ben/client.cpp.s

tests_ben/tests.o: tests_ben/tests.cpp.o

.PHONY : tests_ben/tests.o

# target to build an object file
tests_ben/tests.cpp.o:
	$(MAKE) -f CMakeFiles/tests_app.dir/build.make CMakeFiles/tests_app.dir/tests_ben/tests.cpp.o
.PHONY : tests_ben/tests.cpp.o

tests_ben/tests.i: tests_ben/tests.cpp.i

.PHONY : tests_ben/tests.i

# target to preprocess a source file
tests_ben/tests.cpp.i:
	$(MAKE) -f CMakeFiles/tests_app.dir/build.make CMakeFiles/tests_app.dir/tests_ben/tests.cpp.i
.PHONY : tests_ben/tests.cpp.i

tests_ben/tests.s: tests_ben/tests.cpp.s

.PHONY : tests_ben/tests.s

# target to generate assembly for a file
tests_ben/tests.cpp.s:
	$(MAKE) -f CMakeFiles/tests_app.dir/build.make CMakeFiles/tests_app.dir/tests_ben/tests.cpp.s
.PHONY : tests_ben/tests.cpp.s

tests_d/client.o: tests_d/client.cpp.o

.PHONY : tests_d/client.o

# target to build an object file
tests_d/client.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/client.cpp.o
.PHONY : tests_d/client.cpp.o

tests_d/client.i: tests_d/client.cpp.i

.PHONY : tests_d/client.i

# target to preprocess a source file
tests_d/client.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/client.cpp.i
.PHONY : tests_d/client.cpp.i

tests_d/client.s: tests_d/client.cpp.s

.PHONY : tests_d/client.s

# target to generate assembly for a file
tests_d/client.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/client.cpp.s
.PHONY : tests_d/client.cpp.s

tests_d/helpers.o: tests_d/helpers.cpp.o

.PHONY : tests_d/helpers.o

# target to build an object file
tests_d/helpers.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/helpers.cpp.o
.PHONY : tests_d/helpers.cpp.o

tests_d/helpers.i: tests_d/helpers.cpp.i

.PHONY : tests_d/helpers.i

# target to preprocess a source file
tests_d/helpers.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/helpers.cpp.i
.PHONY : tests_d/helpers.cpp.i

tests_d/helpers.s: tests_d/helpers.cpp.s

.PHONY : tests_d/helpers.s

# target to generate assembly for a file
tests_d/helpers.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/helpers.cpp.s
.PHONY : tests_d/helpers.cpp.s

tests_d/packet.o: tests_d/packet.cpp.o

.PHONY : tests_d/packet.o

# target to build an object file
tests_d/packet.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/packet.cpp.o
.PHONY : tests_d/packet.cpp.o

tests_d/packet.i: tests_d/packet.cpp.i

.PHONY : tests_d/packet.i

# target to preprocess a source file
tests_d/packet.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/packet.cpp.i
.PHONY : tests_d/packet.cpp.i

tests_d/packet.s: tests_d/packet.cpp.s

.PHONY : tests_d/packet.s

# target to generate assembly for a file
tests_d/packet.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/packet.cpp.s
.PHONY : tests_d/packet.cpp.s

tests_d/string.o: tests_d/string.cpp.o

.PHONY : tests_d/string.o

# target to build an object file
tests_d/string.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/string.cpp.o
.PHONY : tests_d/string.cpp.o

tests_d/string.i: tests_d/string.cpp.i

.PHONY : tests_d/string.i

# target to preprocess a source file
tests_d/string.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/string.cpp.i
.PHONY : tests_d/string.cpp.i

tests_d/string.s: tests_d/string.cpp.s

.PHONY : tests_d/string.s

# target to generate assembly for a file
tests_d/string.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/string.cpp.s
.PHONY : tests_d/string.cpp.s

tests_d/tests.o: tests_d/tests.cpp.o

.PHONY : tests_d/tests.o

# target to build an object file
tests_d/tests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/tests.cpp.o
.PHONY : tests_d/tests.cpp.o

tests_d/tests.i: tests_d/tests.cpp.i

.PHONY : tests_d/tests.i

# target to preprocess a source file
tests_d/tests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/tests.cpp.i
.PHONY : tests_d/tests.cpp.i

tests_d/tests.s: tests_d/tests.cpp.s

.PHONY : tests_d/tests.s

# target to generate assembly for a file
tests_d/tests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_d/tests.cpp.s
.PHONY : tests_d/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tests_app"
	@echo "... ben"
	@echo "... tests"
	@echo "... example-async"
	@echo "... example-sync"
	@echo "... lwmqtt_d"
	@echo "... lwmqtt"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... zlib"
	@echo "... uninstall"
	@echo "... libcurl"
	@echo "... cpr"
	@echo "... ben_d/CloudConnect.o"
	@echo "... ben_d/CloudConnect.i"
	@echo "... ben_d/CloudConnect.s"
	@echo "... ben_d/MQTTClient.o"
	@echo "... ben_d/MQTTClient.i"
	@echo "... ben_d/MQTTClient.s"
	@echo "... ben_d/SSLConnection.o"
	@echo "... ben_d/SSLConnection.i"
	@echo "... ben_d/SSLConnection.s"
	@echo "... ben_d/Socket.o"
	@echo "... ben_d/Socket.i"
	@echo "... ben_d/Socket.s"
	@echo "... ben_d/main.o"
	@echo "... ben_d/main.i"
	@echo "... ben_d/main.s"
	@echo "... ben_d/mainAruba.o"
	@echo "... ben_d/mainAruba.i"
	@echo "... ben_d/mainAruba.s"
	@echo "... examples/async.o"
	@echo "... examples/async.i"
	@echo "... examples/async.s"
	@echo "... examples/sync.o"
	@echo "... examples/sync.i"
	@echo "... examples/sync.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/helpers.o"
	@echo "... src/helpers.i"
	@echo "... src/helpers.s"
	@echo "... src/os/unix.o"
	@echo "... src/os/unix.i"
	@echo "... src/os/unix.s"
	@echo "... src/packet.o"
	@echo "... src/packet.i"
	@echo "... src/packet.s"
	@echo "... src/string.o"
	@echo "... src/string.i"
	@echo "... src/string.s"
	@echo "... tests_ben/client.o"
	@echo "... tests_ben/client.i"
	@echo "... tests_ben/client.s"
	@echo "... tests_ben/tests.o"
	@echo "... tests_ben/tests.i"
	@echo "... tests_ben/tests.s"
	@echo "... tests_d/client.o"
	@echo "... tests_d/client.i"
	@echo "... tests_d/client.s"
	@echo "... tests_d/helpers.o"
	@echo "... tests_d/helpers.i"
	@echo "... tests_d/helpers.s"
	@echo "... tests_d/packet.o"
	@echo "... tests_d/packet.i"
	@echo "... tests_d/packet.s"
	@echo "... tests_d/string.o"
	@echo "... tests_d/string.i"
	@echo "... tests_d/string.s"
	@echo "... tests_d/tests.o"
	@echo "... tests_d/tests.i"
	@echo "... tests_d/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

