on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          make gtest
          mkdir build
          cd build
          cmake ..
          make
          ./tests
